apiVersion: v1
kind: Service
metadata:
  name: loans-svc
  namespace: kmskcg-lab
  labels:
    app: svaha-loans
spec:
  selector:
    app: svaha-loans
  ports:
    - protocol: TCP
      port: 9090     # Service port
      targetPort: 9090  # Container port
      nodePort: 30081 # Node port
  type: NodePort
